configure lint-staged
jbx-protocol/juice-interface pull request #1049
Opened 2022-05-22 16:43 UTC by benschac

## What does this PR do and why?

_Provide a description of what this PR does. Link to any relevant GitHub issues,
Notion tasks or Discord discussions._

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the
changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).

2022-05-22 16:43 UTC, benschac commented
Current dependencies on/for this PR:
* main
  * **PR #1048** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1048" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1049** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1049" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1049?utm_source=stack-comment).

2022-05-23 02:20 UTC, benschac commented on .eslintignore
> +.eslintrc.json
I figure eslint is formatted and has a really strict schema so we could ignore it all together.

2022-05-23 02:21 UTC, benschac commented on .eslintrc.json
> +  "overrides": [
I used overrides here, but I guess we could ignore package.json altogether too? Not sure how y'all feel about it.

2022-05-23 02:24 UTC, benschac commented on package.json
> +    "*.{js,jsx,ts,tsx,json,css,md}": [
`lint-staged` will now run on all markdown files, all files that aren't `node_modules`. Jacked this from the docs: https://github.com/okonet/lint-staged#automatically-fix-code-style-with-prettier-for-javascript-typescript-markdown-html-or-css

2022-05-24 01:27 UTC, aeolianeth commented on src/hooks/Poller.ts
> -    function() {
**suggestion**: This hook looks unused. Want to remove it?

2022-05-24 01:28 UTC, aeolianeth approved these changes
Sweet @benschac , this all LGTM. Just one suggestion about deleting a file.

2022-05-24 01:28 UTC, aeolianeth requested changes
.

2022-05-24 23:16 UTC, benschac commented
> Sweet @benschac , this all LGTM. Just one suggestion about deleting a file.

Dope, I can create another PR (diff) addressing the issue.

2022-05-26 13:10 UTC, merged