Improve wallet disconnect transaction modal state
jbx-protocol/juice-interface pull request #1207
Opened 2022-06-11 17:37 UTC by johnnyd-eth

## What does this PR do and why?

Closes #911 

To me, having the button be enabled and the text as 'Connect wallet to ...' and then opening the wallet select would be ideal if not for the fact that this causes a page reload and therefore closes the modal on the user unexpectedly. (reload occurs because setting wallet writes to local storage). 

So then, I think the next best option is just disabling the button with the 'Connect wallet to ...' text, and make the user back out to connect their wallet. 100% open to feedback or other ideas here though.

For every transaction modal that users can get to without a wallet connected, I've implemented this logic. 

## Screenshots or screen recordings

https://user-images.githubusercontent.com/96150256/173198766-10551d5a-309f-40a0-9c97-9868c50e81de.mp4

## Acceptance checklist

- [ ] I have evaluated the
      [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines)
      for this PR.
- [ ] I have tested this PR in
      [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).

2022-06-11 22:18 UTC, aeolianeth requested changes
@johnnyd-eth this probably works for me.

But a reload need not occur - there's a solution to prevent this. I agree it's out of scope of this PR.

There's a few other buttons that we should port this functionality to, which was my original intention with this issue:
- reconfigure modal
- edit project details drawer
- transfer unclaimed tokens
- add to balance

So that we don't duplicate logic, I suggested we have a `TransactorButton` component that we use anywhere we create a transaction. let me know what you think

2022-06-11 22:18 UTC, aeolianeth commented on src/components/shared/TransactionModal.tsx
> +    connectWalletText?: string
**praise** love the prop idea!

2022-06-12 07:44 UTC, johnnyd-eth commented
> @johnnyd-eth this probably works for me.
> 
> But a reload need not occur - there's a solution to prevent this. I agree it's out of scope of this PR.
> 
> There's a few other buttons that we should port this functionality to, which was my original intention with this issue:
> 
> * reconfigure modal
> * edit project details drawer
> * transfer unclaimed tokens
> * add to balance
> 
> So that we don't duplicate logic, I suggested we have a `TransactorButton` component that we use anywhere we create a transaction. let me know what you think

@aeolianeth Yeah good call, I did miss the 'transfer' and 'add to balance' buttons - I created a `TransactorButton` component for them. I think the cleanest solution is still just what I've done with `TransactorModal` since `antd` modals can't take buttons as props.

As for the other instances you've mentioned, they can't be seen or accessed with the wallet disconnected so I didn't think they were worth doing anything for.

2022-06-12 07:45 UTC, johnnyd-eth commented
<img width="1258" alt="Screen Shot 2022-06-12 at 9 34 28 am" src="https://user-images.githubusercontent.com/96150256/173222780-fbeb0b2d-648c-41cc-b1c8-0859ca51a961.png">

Also snuck in a fix to this layout

2022-06-12 08:40 UTC, aeolianeth commented
@johnnyd-eth ah yeah understood.

Merging! Thanks for working on this, really nice UX imrpovement.

2022-06-12 08:40 UTC, aeolianeth approved these changes

2022-06-12 08:40 UTC, merged