Fix Sticker Aspect Ratio in Safari
jbx-protocol/juice-interface pull request #1362
Opened 2022-07-08 13:05 UTC by benschac

## What does this PR do and why?

_Provide a description of what this PR does. Link to any relevant GitHub issues, Notion tasks or Discord discussions._

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

2022-07-08 13:06 UTC, benschac commented
Current dependencies on/for this PR:
* main
  * **PR #1362** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1362" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1362?utm_source=stack-comment).

2022-07-11 21:30 UTC, aeolianeth commented on src/components/RichNote.tsx
> +            width={140}
**issue**: this compresses non-square image unnaturally.

We should find another solution here! I had a play but couldn't quite get it. Will leave it in your capable hands 🙏 

| my image | image rendered in pament memo |
| --- | --- |
|  <img width="504" alt="Screen Shot 2022-07-11 at 2 03 56 PM" src="https://user-images.githubusercontent.com/94939382/178360030-8a037723-1978-49eb-b5ad-75fad0ca9e36.png"> | <img width="552" alt="Screen Shot 2022-07-12 at 6 46 26 AM" src="https://user-images.githubusercontent.com/94939382/178359797-19d0c370-1229-401f-a6c8-08793a6ab6d6.png"> |

2022-07-11 21:30 UTC, aeolianeth requested changes
Thanks @benschac ! There's one issue I found: https://github.com/jbx-protocol/juice-interface/pull/1362/files#r918365829

🏓

2022-07-26 00:16 UTC, tomquirk commented
@benschac frendly bump here.

2022-08-01 14:51 UTC, benschac commented
I accidentally synced changed in my code editor and pulled in changes from the last two weeks. Going to close this PR and open a new one since the code change is tiny.

2022-08-01 14:51 UTC, closed without merging