ETHERC20 Payment addresses section in owner tools
jbx-protocol/juice-interface pull request #1478
Opened 2022-07-21 19:31 UTC by peripheralist

## What does this PR do and why?

- Makes payment addresses viewable in the owner tools drawer
- Unifies "payment address" language throughout
- Removes "write this down or you'll lose it" message from confirmation modal after deploying a payment address

## Screenshots or screen recordings

<img width="567" alt="image" src="https://user-images.githubusercontent.com/79433522/180300055-efefebd1-925a-4a26-8207-b0fb5718d125.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/79433522/180300083-ca7d435d-e041-4ba7-ac2d-d4d4a323dbf1.png">
<img width="595" alt="image" src="https://user-images.githubusercontent.com/79433522/180300100-7f84d19a-d0b3-4dc4-873b-027dda587d45.png">

## Acceptance checklist

- [x] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [x] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [x] I have tested this PR in dark mode and light mode (if applicable).

2022-07-22 02:58 UTC, tomquirk commented
@wraeth-eth could you please take over the review here? 🙏

2022-07-22 16:23 UTC, wraeth-eth requested changes
Looks good Peri! Just a couple of minor comments surrounding translations, and recommendation of ExternalLink

2022-07-22 16:23 UTC, wraeth-eth commented on src/components/v2/V2Project/ProjectPayersModal.tsx
> +export default function ProjectPayersModal({
Should do a review on this function for where Trans/t is needed

2022-07-22 16:23 UTC, wraeth-eth commented on src/components/Project/ProjectToolsDrawer/ProjectPayersSection.tsx
> +            <a
Recommend using <ExternalLink />

2022-07-22 23:30 UTC, peripheralist commented on src/components/Project/ProjectToolsDrawer/ProjectPayersSection.tsx
> +            <a
...ExternalLink? 😏

2022-07-22 23:31 UTC, peripheralist commented
thank you @wraeth-eth! i really need a linter to remind me to add <Trans> 🤦

2022-07-23 22:01 UTC, tomquirk commented on src/components/v2/V2Project/ProjectPayersModal.tsx
> +          {projectPayers.length
dropping by to say that `plural` is useful/preferred here:

```js
import { plural } from '@lingui/macro'

plural(projectPayers.length, {
    one: '# payment address',
    other: '# payment addresses',
})
```

2022-07-25 16:37 UTC, peripheralist commented
finally solved these i18n issues! thanks @aeolianeth for pointing out the filenames, must have been a merge error. cc @wraeth-eth

2022-07-28 01:06 UTC, nnnnicholas commented
exciting!

2022-07-29 13:51 UTC, tomquirk commented
@wraeth-eth could you give this a final review pls?

2022-07-29 15:45 UTC, wraeth-eth commented on src/components/Project/ProjectToolsDrawer/ProjectPayersSection.tsx
> +            <a
lol yes - sorry. No idea what happened there

2022-07-29 15:55 UTC, wraeth-eth approved these changes

2022-07-29 15:56 UTC, merged