Add token symbol and name fields to NFT rewards
jbx-protocol/juice-interface pull request #1629
Opened 2022-08-01 05:31 UTC by johnnyd-eth

## What does this PR do and why?

- These fields are key for StudioDAO's projects so would be great to get out ASAP
- 
<img width="632" alt="Screen Shot 2022-08-01 at 3 29 28 pm" src="https://user-images.githubusercontent.com/96150256/182078408-c5bc0a14-4240-4baa-922e-ade8e267533d.png">

- Also extends NFT upload limit 10x since we're not using the cloud function anymore 

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

2022-08-02 01:48 UTC, tomquirk requested changes
@johnnyd-eth LGTM coupla suggestions

2022-08-02 01:48 UTC, tomquirk commented on src/components/v2/shared/FundingCycleConfigurationDrawers/NftDrawer/index.tsx
> +          <Form layout="vertical">
Can add requiredMark="optional" here and remove the optional text in the label

2022-08-02 01:48 UTC, tomquirk commented on src/components/v2/shared/FundingCycleConfigurationDrawers/NftDrawer/index.tsx
> +                <TooltipLabel
Can remove the tooltip component and use the `tooltip` prop on form.item instead

2022-08-02 08:56 UTC, johnnyd-eth commented
<img width="609" alt="Screen Shot 2022-08-02 at 6 54 28 pm" src="https://user-images.githubusercontent.com/96150256/182334965-8458b34a-343a-4101-b27d-e0fb62b740b4.png">

<img width="593" alt="Screen Shot 2022-08-02 at 6 54 31 pm" src="https://user-images.githubusercontent.com/96150256/182334980-33fff893-6292-4afd-a539-ce4e1813c2e4.png">

This is how it looks after those two comments @aeolianeth. Just me or it look kinda funky?

2022-08-02 09:01 UTC, johnnyd-eth commented
I've pushed changes addressing those comments, have a play and LMKWYT

2022-08-03 02:07 UTC, tomquirk commented
@johnnyd-eth perfect thanks. added a sneaky empty

<img width="620" alt="Screen Shot 2022-08-03 at 12 04 16 PM" src="https://user-images.githubusercontent.com/12551741/182508677-08a50378-dbfb-4cf8-8ea8-ce874f1df3d5.png">

2022-08-03 02:07 UTC, tomquirk approved these changes

2022-08-03 02:07 UTC, merged