[1/x] add venft contracts to loader
jbx-protocol/juice-interface pull request #1654
Opened 2022-08-03 10:38 UTC by jmilldotdev

## What does this PR do and why?

_Provide a description of what this PR does. Link to any relevant GitHub issues, Notion tasks or Discord discussions._

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

2022-08-03 10:38 UTC, jmilldotdev commented
Current dependencies on/for this PR:
* main
  * **PR #1654** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1654" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1654?utm_source=stack-comment).

2022-08-08 05:05 UTC, tomquirk requested changes
See inline comments

2022-08-08 05:05 UTC, tomquirk commented on package.json
> +    "@jbx-protocol/ve-nft": "^0.0.6",
**suggestion**: should we lock the version?

```suggestion
    "@jbx-protocol/ve-nft": "0.0.6",
```

2022-08-09 07:28 UTC, tomquirk approved these changes

2022-08-09 09:00 UTC, merged