Add translations, add tx
jbx-protocol/juice-interface pull request #1656
Opened 2022-08-03 10:38 UTC by jmilldotdev

## What does this PR do and why?

_Provide a description of what this PR does. Link to any relevant GitHub issues, Notion tasks or Discord discussions._

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

2022-08-03 10:39 UTC, jmilldotdev commented
Current dependencies on/for this PR:
* main
  * **PR #1654** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1654" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1655** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1655" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1656** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1656" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1656?utm_source=stack-comment).

2022-08-08 05:09 UTC, tomquirk requested changes
@jmilldotdev this LGTM. Will need to rebase the entire stack on `main` though; we shouldn't have `messages.po` files in PRs anymore <3

2022-08-08 05:09 UTC, tomquirk commented on src/hooks/veNft/transactor/LaunchVeNftTx.ts
> +        projectId, // _projectId
**praise** ty for the arg comments!

2022-08-09 07:30 UTC, tomquirk commented
@jmilldotdev looks like some whacky merge conflicts in the translations files.

Give it a `git checkout main -- src/locales` and run extract again. Should be way easier in future, thanks for bearing with the current process <3

2022-08-09 09:16 UTC, merged