[7/x] allow locking project token
jbx-protocol/juice-interface pull request #1660
Opened 2022-08-03 10:40 UTC by jmilldotdev

## What does this PR do and why?

_Provide a description of what this PR does. Link to any relevant GitHub issues, Notion tasks or Discord discussions._

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

2022-08-03 10:40 UTC, jmilldotdev commented
Current dependencies on/for this PR:
* main
  * **PR #1654** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1654" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1655** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1655" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1656** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1656" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #1657** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1657" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #1658** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1658" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #1659** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1659" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #1660** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1660" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1660?utm_source=stack-comment).

2022-08-08 05:18 UTC, tomquirk requested changes
See inline comments

2022-08-08 05:18 UTC, tomquirk commented on src/components/veNft/formControls/VeNftTokenSelectInput.tsx
> +    <h3>
**suggestion** for semantic juice, perhaps we could remove the wrapping `h3` and style the `label` accordingly instead?

2022-08-09 07:30 UTC, tomquirk approved these changes

2022-08-09 09:47 UTC, merged