[1/x] split project page into project info component
jbx-protocol/juice-interface pull request #1714
Opened 2022-08-11 08:23 UTC by jmilldotdev

## What does this PR do and why?

_Provide a description of what this PR does. Link to any relevant GitHub issues, Notion tasks or Discord discussions._

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

2022-08-11 08:23 UTC, jmilldotdev commented
Current dependencies on/for this PR:
* main
  * **PR #1714** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1714" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1714?utm_source=stack-comment).

2022-08-15 05:46 UTC, tomquirk requested changes

2022-08-15 05:46 UTC, tomquirk commented on src/components/v2/V2Project/V2ProjectHeaderActions.tsx
> +              onClick={handleSettingsPageButtonClick}
**suggestion** for accessibility, lets make this a real link. Not exactly sure if Next Link will work, but `<Button href="/v2/p/${projectId}/settings">` does.

2022-08-15 05:46 UTC, tomquirk commented on src/pages/v2/p/[projectId]/components/V2Dashboard.tsx
> +        <V2Project selectedPage="info" />
**suggestion** can we use the URL as a single source of truth? In other words, can we use the URL alone to determine the render state?

2022-08-15 05:46 UTC, tomquirk commented on src/components/v2/V2Project/index.tsx
> +      </Space>
**question** is this the final design?

2022-08-15 05:48 UTC, tomquirk commented
@jmilldotdev looking good!

I'm not sure if there's changes to routing later on in the stack. If there are, I think we should consolidate them to this PR. Let's get this PR to:
- reorganize the files appropriately (V2ProjectInfo etc)
- Include the final button UI (for getting to and from the settings page)
- Handle routing and page-switching logic.

That way we set a solid foundation for the PRs up the stack 🙌

2022-08-31 22:30 UTC, tomquirk commented
Closing in favor of https://github.com/jbx-protocol/juice-interface/pull/1875

2022-09-11 00:09 UTC, closed without merging