Refactor project pay form
jbx-protocol/juice-interface pull request #2087
Opened 2022-09-30 05:34 UTC by tomquirk

2022-09-30 05:46 UTC, tomquirk commented
@johnnyd-eth can you pls review this one instead? It affects NFT rewards, so want to make sure nothings broken. Cheers.

2022-10-02 00:17 UTC, johnnyd-eth commented on src/components/v2v3/V2V3Project/V2V3Project.tsx
> +          <V2V3PayProjectFormProvider>
**excellent**

2022-10-02 00:21 UTC, johnnyd-eth commented
Awesome cleanup @tomquirk. Code is great. 

Noticed a regression in the NFT rewards no longer being linked to the pay input:
1. Clicking NFTs doesn't fill the pay input
2. Filling pay input doesn't select the appropriate NFT

https://user-images.githubusercontent.com/96150256/193432802-c79d68a0-992a-4573-8e37-1444a0879f60.mp4

2022-10-02 00:22 UTC, johnnyd-eth commented
Other than that, all looking good

2022-10-02 00:23 UTC, johnnyd-eth requested changes
.

2022-10-03 06:29 UTC, tomquirk commented
ah shiet, thanks @johnnyd-eth . Realized the problem. Fixed it 🏓

2022-10-03 06:49 UTC, tomquirk commented
@johnnyd-eth tested v1, v2 and nft rewards pay, all looking gucci. gonna merge

2022-10-03 06:49 UTC, merged