fix decimal bug in mint rate
jbx-protocol/juice-interface pull request #2324
Opened 2022-10-23 20:50 UTC by jmilldotdev

## What does this PR do and why?

Closes #2294

2022-10-24 00:22 UTC, johnnyd-eth requested changes
Thanks for picking this up @jmilldotdev, LGTM. Good safeguard here. Wondering if it might also be worth adding the `isInteger` prop to `FormattedNumberInput` in `MintRateFormItem` to avoid any confusion of users thinking they can have decimal mint rates?

2022-10-24 12:29 UTC, jmilldotdev reviewed
added

2022-10-25 02:16 UTC, johnnyd-eth approved these changes

2022-10-25 02:16 UTC, merged

2022-10-25 02:16 UTC, johnnyd-eth commented
Sweeeet LGTM! Thank you ser