Create: Change copy for payouts
jbx-protocol/juice-interface pull request #2511
Opened 2022-11-13 23:15 UTC by wraeth-eth

## What does this PR do and why?

_Provide a description of what this PR does. Link to any relevant GitHub issues, Notion tasks or Discord discussions._

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

2022-11-13 23:16 UTC, wraeth-eth commented
Current dependencies on/for this PR:
* main
  * **PR #2510** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/2510" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #2511** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/2511" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/2511?utm_source=stack-comment).

2022-11-16 03:53 UTC, tomquirk requested changes
See inline comments

2022-11-16 03:53 UTC, tomquirk commented on src/components/Create/Create.tsx
> +                    like to pay each funding cycle.
```suggestion
                    Select how you would like to distribute
                    payouts. Then, choose which Ethereum wallets to pay each funding cycle.
```

2022-11-16 22:00 UTC, tomquirk approved these changes

2022-11-17 23:21 UTC, wraeth-eth commented
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/2511?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: XJjT605R1Sdi2CUgZUbX

2022-11-17 23:49 UTC, merged