Funding cycle section of FC card DIFF VIEW
jbx-protocol/juice-interface pull request #2569
Opened 2022-11-25 05:30 UTC by johnnyd-eth

## What does this PR do and why?

<img width="1088" alt="Screen Shot 2022-11-25 at 3 30 04 pm" src="https://user-images.githubusercontent.com/96150256/203907651-54824981-4797-4304-a2e7-fc2df07a17d4.png">

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

2022-12-07 23:51 UTC, tomquirk commented on src/components/v2v3/V2V3Project/V2V3FundingCycleSection/FundingCycleDetails/FundingCycleListItem.tsx
> +      : undefined
@johnnyd-eth now that we have tailwind, can you pls update these colors to use Tailwind colors?

2022-12-07 23:52 UTC, tomquirk commented
@johnnyd-eth this is so huge! Sorry for the delay in review, looks all good i think, just one comment + conflicts to fix.

2022-12-16 23:00 UTC, wraeth-eth requested changes
LFG!!!! Love this feature. Just made some comments about tailwindcss stuff

2022-12-17 09:49 UTC, johnnyd-eth commented on src/components/v2v3/V2V3Project/V2V3FundingCycleSection/FundingCycleDetails/FundingCycleListItem.tsx
> +      style={{
Thank you ser, very helpful 💪

2022-12-17 09:55 UTC, johnnyd-eth commented
Thanks for these tips @wraeth-eth, I've applied these changes! Good to go now?

2022-12-17 22:09 UTC, wraeth-eth approved these changes

2022-12-17 22:37 UTC, merged