add pauseTransfer flag option to rules
jbx-protocol/juice-interface pull request #2876
Opened 2023-01-24 05:15 UTC by wraeth-eth

## What does this PR do and why?

_Provide a description of what this PR does. Link to any relevant GitHub issues, Notion tasks or Discord discussions._

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

2023-01-24 05:15 UTC, wraeth-eth commented
Current dependencies on/for this PR:
* main
  * **PR #2876** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/2876" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/2876?utm_source=stack-comment).

2023-01-24 15:22 UTC, mejango requested changes

2023-01-24 15:22 UTC, mejango commented on src/components/v2v3/V2V3Project/V2V3ProjectSettings/pages/ReconfigureFundingCycleSettingsPage/FundingAttributes.tsx
> +              ? t`Transfers are paused`
"Project token transfers are paused/unpaused. This does not apply to ERC-20 tokens if issued."

2023-01-24 15:22 UTC, mejango commented on src/components/v2v3/shared/FundingCycleConfigurationDrawers/RulesDrawer/RulesForm/RulesForm.tsx
> +              <Trans>Pause transfers</Trans>
Pause project token transfers. Does not apply to ERC-20 tokens if issued.

2023-01-24 15:22 UTC, mejango commented on src/locales/messages.pot
> +msgid "Transfers are paused"
Transfers of project tokens are paused. This does not apply to ERC-20 tokens if issued.

2023-01-24 15:22 UTC, mejango commented on src/locales/messages.pot
> +msgid "When enabled, all transfers will be paused."
transfers to project tokens will be paused. This does not apply to ERC-20 tokens if issued.

2023-01-24 15:22 UTC, mejango commented on src/locales/messages.pot
> +msgid "When enabled, transfers will be paused."
...project token transfers will be paused. This does not apply to ERC-20 tokens if issued.

2023-01-24 15:22 UTC, mejango commented on src/components/Create/components/pages/ReconfigurationRules/ReconfigurationRulesPage.tsx
> +              extra={t`When enabled, transfers will be paused.`}
... project token transfers will be paused. This does not apply to ERC-20 tokens if issued.

2023-01-30 01:17 UTC, johnnyd-eth approved these changes
Tested this and it's all working well, and code looks great. Will merge!

2023-01-30 01:17 UTC, merged