Better project card mobile styling
jbx-protocol/juice-interface pull request #3162
Opened 2023-03-06 23:22 UTC by peripheralist

## What does this PR do and why?

- Removes border, reduces padding, and shrinks logo images for ProjectCards and TrendingProjectCards on mobile
- Reduces container x padding on TrendingSection on landing page
- TrendingProjectCards now have trending rank number inset in logo image
- No changes to desktop

## Screenshots or screen recordings

<img width="373" alt="image" src="https://user-images.githubusercontent.com/79433522/223279017-9e555b54-add1-4bcc-8298-a6dc4ddf438b.png">

<img width="373" alt="image" src="https://user-images.githubusercontent.com/79433522/223279099-4940ef35-d648-4a56-94c3-4fbf4041dda8.png">

<img width="374" alt="image" src="https://user-images.githubusercontent.com/79433522/223279132-36b4fbd0-c85a-42dc-9a26-320f65664378.png">

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

2023-03-06 23:39 UTC, tomquirk requested changes
LGTM @peripheralist ! just a few suggestions about tailwind media queries in place of `isMobile`

2023-03-06 23:39 UTC, tomquirk commented on src/components/ProjectCard.tsx
> +              : 'rounded-sm border border-solid border-smoke-300 py-6 px-5 transition-colors hover:border-smoke-500 dark:border-slate-300 dark:hover:border-slate-100'
**suggestion** we can use tailwind media queries for all this. can slap `md:<class>` for all of the false case of the turnary.

2023-03-06 23:39 UTC, tomquirk commented on src/components/ProjectCard.tsx
> +              className={isMobile ? 'h-24 w-24' : 'h-28 w-28'}
**suggestion** same here w tailwind media queries

2023-03-06 23:39 UTC, tomquirk commented on src/pages/projects/TrendingProjectCard.tsx
> +              isMobile
tailwind media q

2023-03-06 23:39 UTC, tomquirk commented on src/pages/projects/TrendingProjectCard.tsx
> +                    isMobile ? 'text-base' : 'text-xl',
tailwind media q

2023-03-06 23:39 UTC, tomquirk commented on src/pages/projects/TrendingProjectCard.tsx
> +                <div className="font-medium text-black dark:text-slate-100">
to hide/show elems instead of `isMobile`, can do `hidden md:block`

2023-03-06 23:40 UTC, tomquirk commented on src/pages/projects/TrendingProjectCard.tsx
> +            {isMobile ? (
same here prooobably: https://github.com/jbx-protocol/juice-interface/pull/3162#discussion_r1127166946

2023-03-07 04:29 UTC, peripheralist commented
thank you @tomquirk ! updated

2023-03-07 06:47 UTC, tomquirk approved these changes
siiiick thank you @peripheralist , full send!

2023-03-07 06:47 UTC, merged