Twitter metadata fixes
jbx-protocol/juice-interface pull request #3264
Opened 2023-03-21 03:00 UTC by filipviz

- Fallback to defaults on individual tags (instead of only when project metadata was missing)
- Use [ipfs.io public gateway](https://ipfs.io/ipfs/) project page logo Twitter tags.
- Update site Twitter tag to always be `config.twitter.site`, which is now https://juicebox.money. See https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

2023-03-21 03:06 UTC, tomquirk requested changes
awesome keen for this, couple of suggestions

2023-03-21 03:06 UTC, tomquirk commented on src/pages/p/[handle]/index.page.tsx
> +          handle: metadata?.twitter ? metadata.twitter : undefined,
```suggestion
          creator: metadata?.twitter,
          handle: metadata?.twitter,
```

2023-03-21 03:06 UTC, tomquirk commented on src/pages/v2/p/[projectId]/index.page.tsx
> +        title={metadata?.name ? metadata.name : undefined}
```suggestion
        title={metadata?.name}
```

2023-03-21 03:06 UTC, tomquirk commented on src/pages/v2/p/[projectId]/index.page.tsx
> +          handle: metadata?.twitter ? metadata.twitter : undefined,
```suggestion
          creator: metadata?.twitter,
          handle: metadata?.twitter,
```

or at the very least we can do `metadata?.twitter ?? undefined`

2023-03-21 17:52 UTC, filipviz commented on src/pages/p/[handle]/index.page.tsx
> +          handle: metadata?.twitter ? metadata.twitter : undefined,
Great point. Quite silly.

2023-03-23 03:07 UTC, tomquirk commented
@filipviz how u feelin bout this?

2023-03-23 14:18 UTC, filipviz commented
@tomquirk good to go!

2023-03-23 22:39 UTC, tomquirk approved these changes
Awesome filip thank you!

2023-03-23 22:39 UTC, merged