Peri/number input decimals fix
jbx-protocol/juice-interface pull request #3954
Opened 2023-08-07 22:45 UTC by peripheralist

This PR removes the Antd number input from JuiceInputNumber and replaces it with custom logic. This avoids an issue where numbers were previously being limited to JS MAX_INT, presumably because the Antd component was doing some Number logic under the hood.

2023-08-07 22:54 UTC, peripheralist commented on src/components/inputs/JuiceInputNumber.tsx
> +        'text-primary stroke-secondary rounded-lg border border-smoke-300 bg-smoke-50 px-4 py-2 text-black dark:border-slate-300 dark:bg-slate-600 dark:text-slate-100 dark:placeholder:text-slate-300'
adds some styling that was previously defined in css for .ant-number-input

2023-08-09 08:05 UTC, johnnyd-eth commented
Code looks dope @peripheralist! Just gave it a whirl and noticed typing it decimals points don't seem to be working anywhere. LGTM outside of that

2023-08-09 08:05 UTC, johnnyd-eth requested changes
(Decimals not working)

2023-08-09 19:43 UTC, peripheralist commented
thanks for taking a careful look @johnnyd-eth 🙏 fixed now

<img width="212" alt="image" src="https://github.com/jbx-protocol/juice-interface/assets/79433522/cc96b13e-9cf3-489a-b4cc-35216d001e11">

2023-08-10 06:20 UTC, johnnyd-eth approved these changes
Sweet, LGTM then!

2023-08-11 00:10 UTC, merged